name: Process Markdown & Build Docs

on:
  push:
    branches:
      - main
    paths:
      - 'platform/**/**/*.md'
      - 'homepage/**'
      - 'requirements.txt'
      - 'scripts/**'

jobs:
  process-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt install -y \
          tox \
          texlive-latex-extra \
          texlive-xetex \
          latexmk \
          python3-pip \
          fonts-freefont-ttf \
          texlive-lang-chinese
                
      - name: Process Markdown Images
        run: tox -e process_md_images
        
      - name: Build HTML
        run: tox -e html

      - name: Build PDF
        run: tox -e pdf
            
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./docs_build
