name: Process Markdown & Build Docs

on:
  push:
    branches:
      - main
    paths:
      - 'platform/**/**/*.md'
      - 'homepage/**'
      - 'requirements.txt'
      - 'scripts/**'

jobs:
  process-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tox
        run: pip install tox

      - name: Process Markdown Images
        run: tox -e process_md_images
        
      - name: Build HTML
        run: tox -e build_docs
            
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./docs_build
