name: Process Markdown & Build Docs

on:
  push:
    branches:
      - main
    paths:
      - 'platform/**/**/*.md'
      - 'homepage/**'
      - 'requirements.txt'
      - 'scripts/**'

jobs:
  process-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tox
        run: pip install tox

      - name: Process Markdown Images
        run: tox -e process_md_images
        env:
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Deploy Docs
        run: tox -e build_docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
